const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bridge', {
  usuario: (() => { try { return require('os').userInfo().username; } catch { return ''; } })(),
  onEvent: fn => ipcRenderer.on('event', (_e, ev) => fn(ev)),
  onExpired: fn => ipcRenderer.on('expired', (_e, id) => fn(id)),
  onDemo: fn => ipcRenderer.on('demo', () => fn()),
  tts: text => ipcRenderer.invoke('tts', text),
  onActualizacion: fn => ipcRenderer.on('actualizacion', (_e, i) => fn(i)),
  actualizarAhora: () => ipcRenderer.send('upd-ahora'),
  actualizarLuego: () => ipcRenderer.send('upd-luego'),
  onDemoFlow: fn => ipcRenderer.on('demo-flow', () => fn()),
  onPresentacion: fn => ipcRenderer.on('presentacion', () => fn()),
  onCursor: fn => ipcRenderer.on('cursor', (_e, p) => fn(p)),
  onDecided: fn => ipcRenderer.on('decided', (_e, id, b) => fn(id, b)),
  onUsage: fn => ipcRenderer.on('usage', (_e, u) => fn(u)),
  focusTerminal: sid => ipcRenderer.invoke('focus-terminal', sid),
  robotState: st => ipcRenderer.send('robot-state', st),
  onPoke: fn => ipcRenderer.on('poke', () => fn()),
  onNotif: fn => ipcRenderer.on('notif', (_e, n) => fn(n)),
  talk: (text, origin) => ipcRenderer.invoke('talk', text, origin),
  sesChat: sid => ipcRenderer.invoke('ses-chat', sid),
  sesSend: (sid, text) => ipcRenderer.invoke('ses-send', sid, text),
  listen: () => ipcRenderer.invoke('listen'),
  onSay: fn => ipcRenderer.on('say', (_e, t) => fn(t)),
  onListenKey: fn => ipcRenderer.on('listen-key', () => fn()),
  onCard: fn => ipcRenderer.on('card', (_e, c) => fn(c)),
  onUrgent: fn => ipcRenderer.on('urgent', (_e, c) => fn(c)),
  onCardDone: fn => ipcRenderer.on('card-done', (_e, id) => fn(id)),
  onAnswer: fn => ipcRenderer.on('answer', (_e, a) => fn(a)),
  onThinking: fn => ipcRenderer.on('thinking', (_e, v) => fn(v)),
  cardAction: (id, action, text) => ipcRenderer.invoke('card-action', id, action, text),
  decide: (id, behavior) => ipcRenderer.send('decision', id, behavior),
  interactive: on => ipcRenderer.send('interactive', on),
  onIconSize: fn => ipcRenderer.on('icon-size', (_e, px) => fn(px)),
  onNombre: fn => ipcRenderer.on('nombre', (_e, n) => fn(n)),
  onMudanza: fn => ipcRenderer.on('mudanza', (_e, dir) => fn(dir)),
});
